#!/usr/bin/env perl
use strict;
use warnings;

use Getopt::Long qw(:config no_ignore_case bundling);
use Algorithm::FEC;
use IPC::Run qw(run);
use MIME::Base64;
use Number::Range;

sub read_image {
	my %args = @_;
	my %data;

	my $codes;
	run
		["convert", @{$args{convert_options}}, $args{filename}, "pnm:-"],
		"|", ["zbarimg", "--raw", "--", "-"], ">", \$codes;

	foreach my $code (split(/\n/, $codes)) {
		if ($code =~ /^FI(.+)$/) {
			# fileid
			$data{fileid} = $1;
		} elsif ($code =~ /^(OS|LE)([0-9a-f]+)$/) {
			# offset/length
			$data{{OS => "offset", LE => "length"}->{$1}} = oct("0x$2");
		} elsif ($code =~ /^DBNONE\s*$/) {
			# no deleted blocks
			$data{deleted_blocks} = 1;
		} elsif ($code =~ /^DB(.*)$/) {
			# deleted blocks, fill them with null bytes.
			foreach my $bid (Number::Range->new($1)->range()) {
				push(@{$data{data_indices}}, $bid);
				push(@{$data{data}}        , "\0" x 30);
			}
			$data{deleted_blocks} = 1;
		} elsif ($code =~ /^([0-9a-f]+):([A-Za-z0-9+\/=]{1,40})$/) {
			# data
			push(@{$data{data_indices}}, oct("0x$1"));
			push(@{$data{data}}        , decode_base64($2));
		} else {
			warn("Ignoring unknown barcode input \"$code\"");
		}
	}

	foreach (qw(fileid offset length deleted_blocks)) {
		die("Required header field \"$_\" not found in image") if (!exists($data{$_}));
	}
	delete($data{deleted_blocks});

	if (@{$data{data}} < 128) {
		die("Could only retrieve " . scalar(@{$data{data}}) . " data lines from image \"$args{filename}\" - need at least 128");
	}

	my $fec = Algorithm::FEC->new(128, 160, 30);
	my @f_d = @{$data{data}}[0..127];
	my @f_i = @{$data{data_indices}}[0..127];
	$fec->set_decode_blocks(\@f_d, \@f_i);
	$fec->decode();

	$data{data} = join("", @f_d);
	delete($data{data_indices});

	$data{data} = substr($data{data}, 0, $data{length});

	return \%data;
}

my %params = (
	filename => $ARGV[0],
	convert_options => ["-threshold", "75%"],
);

print read_image(%params)->{data};
